/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGates, IGatesInterface } from "../IGates";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "snapshotId",
        type: "bytes32",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGates__factory {
  static readonly abi = _abi;
  static createInterface(): IGatesInterface {
    return new utils.Interface(_abi) as IGatesInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGates {
    return new Contract(address, _abi, signerOrProvider) as IGates;
  }
}
