/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IGatesInterface extends utils.Interface {
  contractName: "IGates";
  functions: {
    "verify(address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "verify",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface IGates extends BaseContract {
  contractName: "IGates";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGatesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verify(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verify(address,bytes32)"(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  verify(
    user: string,
    snapshotId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verify(address,bytes32)"(
    user: string,
    snapshotId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    verify(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verify(address,bytes32)"(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verify(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(address,bytes32)"(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verify(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(address,bytes32)"(
      user: string,
      snapshotId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
