export const ENDPOINTS = {
  QUICKNODE_MAINNET:
    'https://lingering-silent-river.discover.quiknode.pro/f428e3656cb005f91d0a16d767e9284ee9690bb2/',
  COINBASE_MAINNET_NODE: 'https://mainnet.ethereum.coinbasecloud.net',
  COINBASE_MAINNET_USERNAME: '4M2MERJIAORAU6GFEYE7',
  COINBASE_MAINNET_PASSWORD: 'KLDW6E4V7MXEJ7ICIPVEWFTGI7XKHGPJD2T6J6S3',
  COINBASE_GOERLI_NODE: 'https://goerli.ethereum.coinbasecloud.net',
  COINBASE_GOERLI_USERNAME: 'DRZ2OWIB5G77W6DZBEPV',
  COINBASE_GOERLI_PASSWORD: 'BZTD4UYUWJLLGVY2RS3V45HUNA42Z7KEJKKKP2FM',
};
